export const UPDATE_DATA = 'UPDATE_DATA';
export const UPDATE_SEARCH = 'UPDATE_SEARCH';
export const UPDATE_SORT = 'UPDATE_SORT';
export const UPDATE_FILTER = 'UPDATE_FILTER';
export const ADD_NOTIFICATION = 'ADD_NOTIFICATION';
export const DISMISS_NOTIFICATION = 'DISMISS_NOTIFICATION';
